// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzykładowyKolos2.Context;

#nullable disable

namespace PrzykładowyKolos2.Migrations
{
    [DbContext(typeof(ApbdContext))]
    [Migration("20240607091801_pls")]
    partial class pls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuzykUtwor", b =>
                {
                    b.Property<int>("MuzycyIdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("UtworyIdUtwor")
                        .HasColumnType("int");

                    b.HasKey("MuzycyIdMuzyk", "UtworyIdUtwor");

                    b.HasIndex("UtworyIdUtwor");

                    b.ToTable("MuzykUtwor");
                });

            modelBuilder.Entity("PharmacyApi.Models.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuzyk"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk");

                    b.ToTable("Muzycy");
                });

            modelBuilder.Entity("PharmacyApi.Models.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtwor"));

                    b.Property<float>("CzasTrwania")
                        .HasColumnType("real");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor");

                    b.ToTable("Utwory");
                });

            modelBuilder.Entity("MuzykUtwor", b =>
                {
                    b.HasOne("PharmacyApi.Models.Muzyk", null)
                        .WithMany()
                        .HasForeignKey("MuzycyIdMuzyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApi.Models.Utwor", null)
                        .WithMany()
                        .HasForeignKey("UtworyIdUtwor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
